version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run DB migration
          command: |
            npm run db-department:migrate
      - run:
          name: Run integration testing
          command: |
            npm run test-department
workflows:
  setup:
    jobs:
      - test
