version: 2.1

jobs:
  getting-started:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Getting Started
          command: |
            npm install
            npm run test-department
workflows:
  setup:
    jobs:
      - getting-started
