version: 2.1

jobs:
  getting-started:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Getting Started
          command: |
            npm install
            npm install -g sequelize-cli
            npm run db-department:migrate
            npm run test-department
workflows:
  setup:
    jobs:
      - getting-started
